import '@/styles/globals.css';
import Header from './Header';
import Providers from './Providers';
import Footer from './Footer';


export const metadata = {
  title: 'IQRA_FM Kenya',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Providers>
          <body className='bg-gray-200 h-full dark:bg-zinc-900 transition-all
              duration-700'>
              <Header />
              <div className='max-w-6xl h-1/2 justify-between mx-auto'>
                 {children}
              </div>
              <Footer />
          </body>
       </Providers>  
    </html>
  )
}
