// RootLayout.tsx

import Head from "next/head";
import { ReactNode } from "react";
import Header from "./Header";
import Providers from "./Providers";
import Footer from "./Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

export const metadata = {
  title: "IQRA_FM Kenya",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <>
      <Head>
        {/* Google Tag Manager */}
        <script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-7CVW7897LC"
        ></script>
        <script>
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-7CVW7897LC');
          `}
        </script>
        {/* End Google Tag Manager */}
      </Head>
      <Providers>
        <html lang="en">
          <body className="bg-gray-200 h-full dark:bg-zinc-900 transition-all duration-700 items-center">
            <Header />
            <div className="max-w-full h-1/2 justify-center items-center mx-auto">
              {children}
            </div>
            <Footer />
          </body>
        </html>
      </Providers>
    </>
  );
}
