export const scheduleData = [
  //MONDAY
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Magazeti & Dau",
    hostName: "Nur Said, Sophia, Fahamu Kazungu ",
    time: "7AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Women's corner",
    hostName: "Sameera Galoro & Madina Idd",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Dini ya haki",
    hostName: "Ali salim",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Dini ya haki",
    hostName: "Ali salim",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Somali programme",
    hostName: "John Doe",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Barwani Mashairi",
    hostName: "Barwani",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Salaam",
    hostName: "Ahmed & Madina",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Qur’an translation",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "News/Sports",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Tiba Tibuka",
    hostName: "Fahamu Kazungu/Ahmed",
    time: "7:45PM-8:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Pima Ilmu Yako",
    hostName: "Nur said/Seera",
    time: "8:30PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Mjue Sheikh Wako",
    hostName: "Host",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Monday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
  //TUESDAY
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Magazeti & Dau",
    hostName: "Nur Said, Sophia, Fahamu Kazungu ",
    time: "7AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Women's corner",
    hostName: "Sameera Galoro & Madina Idd",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Biashara na ajira",
    hostName: "Ali salim & Ramla",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Mahusiano katika jamii",
    hostName: "Madina & Muumin",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Somali programme",
    hostName: "Host",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Mawaaidha",
    hostName: "Ust.Hassan Kilele & Nubi",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Salaam",
    hostName: "Ahmed & Madina",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Qur’an translation",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "News",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "40-An-Nawawiy",
    hostName: "Host",
    time: "7:45PM-8:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Stories of the Prophets",
    hostName: "Host",
    time: "8:30PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Maisha Ughaibuni",
    hostName: "Ali & Ramla Abdi",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Tuesday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
  //WEDNESDAY
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Magazeti & Dau",
    hostName: "Nur Said, Sophia, Fahamu Kazungu ",
    time: "7AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Women's corner",
    hostName: "Madina Idd",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Biashara na ajira",
    hostName: "Ali salim & Ramla",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Jua haki na Majukumu",
    hostName: "Sophia",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Somali programme",
    hostName: "Host",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Abla",
    hostName: "Host",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Salaam",
    hostName: "Ahmed & Madina",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Qur’an translation",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "News/Sports",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Tiba Tibuka",
    hostName: "Fahamu Kazungu/Ahmed",
    time: "7:45PM-8:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Pima Ilmu Yako",
    hostName: "Nur said/Seera",
    time: "8:30PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Mjue Sheikh Wako",
    hostName: "Host",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Wednesday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
  //THURSDAY
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Magazeti & Dau",
    hostName: "Nur Said, Sophia, Fahamu Kazungu ",
    time: "7AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Women's corner",
    hostName: "Sameera Galoro & Madina Idd",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Biashara na Ajira",
    hostName: "Ali salim & Ramla",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Tatizo liko Wapi",
    hostName: "Sophia",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Somali programme",
    hostName: "Host",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Luo Mawaidha",
    hostName: "Sheikh...",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Salaam",
    hostName: "Ahmed & Madina",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Qur’an translation",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "News/Sports",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Nasheed 15minutes",
    hostName: "Playing...",
    time: "7:45PM-8:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Dini ya haki",
    hostName: "Ust....",
    time: "8:30PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "The untold stories",
    hostName: "Ali & Ramla",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Thursday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
  //FRIDAY
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Dau(Ali & Sophia) ",
    hostName: "Bustani la manufaa(Ali Salim)",
    time: "7AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Suratul-Kahf",
    hostName: "Sheikh...",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Suratul-Yaseen",
    hostName: "Sheikh...",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Khutbah(Sermon)",
    hostName: "Al-Jumuah",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Somali programme",
    hostName: "John Doe",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Kikuyu Hour",
    hostName: "Host...",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Salaam & Shairi",
    hostName: "Ali, Ahmed & Madina",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Burdah",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "News",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Visa vya maswahaba",
    hostName: "Host...",
    time: "7:45PM-8:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Straight path",
    hostName: "English",
    time: "8:30PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "40-An-Nawawiy",
    hostName: "Host",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Friday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
  //SATURDAY
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Magazeti(Nur Said)",
    hostName: "Kikoto-Fahamu Kazungu ",
    time: "7AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Women's corner",
    hostName: "Sameera Galoro & Firdaus",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Urdu",
    hostName: "Sheikh...",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "program",
    hostName: "Ramla & Adila",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Somali programme",
    hostName: "Host",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Lishe bora/Mashairi",
    hostName: "Host",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Sports",
    hostName: "Shuaib & Ahmed",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Qur’an translation",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "News",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Bulughul maram",
    hostName: "Baabad",
    time: "7:45PM-8:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Biashara na Ajira/Islamic Finance",
    hostName: "Shuaib",
    time: "8:30PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Straight Path",
    hostName: "Host",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Saturday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
  //SUNDAY
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Magazeti",
    hostName: "Sameera Galoro",
    time: "7AM-8:30AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Dau",
    hostName: "Dr. Fahamu & Madina",
    time: "9AM-10AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Arabic",
    hostName: "Gadaffi",
    time: "10AM-11AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Sokomoko",
    hostName: "Khamis & Fuad",
    time: "11AM-12PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Sokomoko",
    hostName: "Khamis & Fuad",
    time: "12PM-1PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Somali programme",
    hostName: "Host",
    time: "1:30PM-3PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "NEWS & Yakupasayo kujua",
    hostName: "Ust Muhammad Abdallah",
    time: "3PM-3:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Barwani Mashairi",
    hostName: "Barwani",
    time: "3:30PM-4:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Darsa za walio silimu",
    hostName: "Reverts sermons",
    time: "4:30PM-5:50PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Dira ya IQRA & Business news",
    hostName: "Host",
    time: "6AM-6:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Qur’an translation",
    hostName: "Sheikh...",
    time: "6:30PM-7:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "News",
    hostName: "Host",
    time: "7:30PM-7:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "MIrathi-Ust. Ibrahim Lethome",
    hostName: "Madina Idd",
    time: "7:45PM-8:45PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Njia ya kufaulu",
    hostName: "Abubakar",
    time: "9:00PM-10PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Prophet Muhammad(SAW)",
    hostName: "Host",
    time: "10:30PM-11:30PM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "Streams",
    hostName: "listening...",
    time: "11:30PM-12:00AM",
  },
  {
    photo: "/management/mosque.jpg",
    day: "Sunday",
    scheduleName: "QUR’AN",
    hostName: "Sheikh...",
    time: "12:00AM-4:30AM",
  },
];
